### PR TITLE
Backend setup PR

### PR DESCRIPTION
**Pull request by oktayozel**
Backend Setup is completed. Can you check and pull.

### CODE REVIEW

**Comment by YavizGuldalf** [comment]
Can you please change the name of this Pull Request before merging, I see no reason for the PR name to include its creator's name.

**Comment by oktayozel** [comment]
> Can you please change the name of this Pull Request before merging, I see no reason for the PR name to include its creator's name.

Sorry it was the name of the branch, so github named it automatically, now fixed.

**Comment by yunusemreozdemir** [comment]
This PR is very large with over 5000 files changed. There may be files tracked that shouldn't be kept in the git repository.

**Comment by Elifnurdeniz** [comment]
Can we make .env file git ignore? We can add an example file for it instead.

**Comment by yunusemreozdemir** [comment]
I see a venv folder with python 3.12 installed in it. I think majority of the files are accounted by this. I think there is no need for venv since we will be working with Docker, even if we need it I don't think we should be keeping it in the repository.

**Comment by yunusemreozdemir** [comment]
app and backend_project folders seem fine although I'm not sure if we should include __pycache__ folders, let's check the best practice on this one.

**Comment by yunusemreozdemir** [comment]
What does mysql_data contain? Should this be version controlled? I think we should set up MySQL with Docker Compose as we did it in previous semester.

**Comment by arastasci** [comment]
you are indeed right @yunusemreozdemir - i've removed unnecessary files. @kaanyolcu22 can you check if the PR is OK now?

**Comment by kaanyolcu22** [comment]
looks good to me

**Pull request merged**
