### PR TITLE
Profile Picture Editing & Display in Mobile

### LINKED ISSUE #807: Mobile: Connect the Edit Profile Picture with Backend & Update Design
## Issue Description
The backend endpoint for uploading custom pictures for a user's profile picture is now ready. We need to connect the mobile design with this endpoint. While working on this, we should also change the edit profile page in the mobile to remove the "Name" field (as it is not used anywhere else, neither backend nor frontend), and also update the profile/other profile pages to display username in place of name.

## Tasks

- [ ] Connect the profile page image to the backend
- [ ] Remove the name field from the EditProfile page
- [ ] Replace the name field with the username field in the profile/other profile pages.

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 14/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 16/12/2024 - 20:00

### PR DESCRIPTION
**Pull request by YavizGuldalf**
Fixes #807.

The main change included in this PR is the ability to actually upload pictures to the backend and then display the profile pictures returned from the backend. While I was working on this, I encountered a few minor bugs related to the followers/following pages of other user profiles, so I also handled them in this PR. With the changes made in this PR, wherever a user card can be found, except in the search page. This is due to the backend not actually returning the profile picture url when performing a search for users. Once that issue is fixed, I will add the profile pictures to the mobile search page as well. However, even though I can't test it, I am pretty sure that the UserCard component will display the profile picture correctly once it is returned correctly from the backend.

### CODE REVIEW

**Comment by aoengin** [comment]
I've tested the feature on an emulated Android device, and it works well. Besides the problem on the search page, there is also an avatar on the home page. It's not a user card, but should we edit this one as well?

**Comment by YavizGuldalf** [comment]
You are absolutely right, the picture in the home page should also display the profile picture. I'll push a commit fixing that today.

**Comment by YavizGuldalf** [comment]
The latest commit should have fixed the issue you mentioned, can you please check again @aoengin?

**Comment by aoengin** [comment]
Well done! Works well.

**Review by aoengin — APPROVED** [review]
Necessary changes are made works well.

**Pull request merged**
