### PR TITLE
refactor(mobile): redesign quiz pages

### LINKED ISSUE #452: Mobile: Redesign the Quiz Pages
## Issue Description
As the mobile team, we've decided to change the design based on the feedback we've collected during our first customer presentation to align with the front-end design. We need to edit the quiz pages to have a similar design to the front end.

## Tasks
- [x] Redesign quiz feed page 
- [x] Redesign quiz details page
- [x] Redesign quiz result page
- [x] Redesign quiz creation pages
- [x] Redesign quiz question pages 

## Estimated Time
**Estimated Time:** 4 hours 

## Deadline
**Deadline:** 01/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @anilanlar 

**Review Deadline:** 02/11/2024 - 23:59

### PR DESCRIPTION
**Pull request by aoengin**
Fixes #452.

# Quiz Feed Page

- Like icons are updated.
- Add icon is updated.
- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
Screenshot 2024-10-29 at 13 16 36

# Quiz Details Page

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
Screenshot 2024-10-28 at 23 54 42

# Quiz Result Page

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
- The recommended quiz card is changed; it's now the same as the cards shown on the quiz feed.
- Placement of the icons and text is changed on the result card.
Screenshot 2024-10-29 at 12 07 50

# Quiz Creation Pages

## Quiz Creation Page 1 - (Quiz Details)

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
- All components are added to a card for a more compact design.

Screenshot 2024-10-29 at 17 49 44

## Quiz Creation Page 2 - (List of Questions)

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
- Update and removal icons are updated.
- Icon for adding new questions is updated.
Screenshot 2024-10-29 at 16 06 32

## Quiz Creation Page 3 - (Question Creation Page)

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
- Buttons and input components are reshaped for a better UI design.
Screenshot 2024-10-29 at 17 50 21

# Quiz Question Page

- General design of the page is changed in accordance with the front-end design (colors, shadows, etc.).
- Quiz question and answers are collected in a card for a better UI design.
Screenshot 2024-10-29 at 13 10 34

**Note:** The navbar will be updated after the navbar update is available on main branch.

### CODE REVIEW

**Comment by YavizGuldalf** [comment]
The redesign looks good, and the addition of shadows was a nice touch, good job. However, when I tested this branch on my mobile phone I encountered a visual bug in the quizQuestion and quizResults page: Some buttons and text are overlapping and the orientation of answer buttons is broken. I am attaching screenshots of the bugs so you can see it. I believe these can  be fixed by adjusting the 'flex' options for some of the components (like shadows). I think choosing an emulator for a device with a lower resolution might let you reproduce the bug.

| Quiz Results Page | Quiz Question Page |
| ----- | - | 
|  | |

**Review by YavizGuldalf — CHANGES_REQUESTED** [review]
The redesign looks good, and the addition of shadows was a nice touch, good job. However, when I tested this branch on my mobile phone I encountered a visual bug in the quizQuestion and quizResults page: Some buttons and text are overlapping and the orientation of answer buttons is broken. I am attaching screenshots of the bugs so you can see it. I believe these can  be fixed by adjusting the 'flex' options for some of the components (like shadows). I think choosing an emulator for a device with a lower resolution might let you reproduce the bug.

| Quiz Results Page | Quiz Question Page |
| ----- | - | 
|  | |

**Comment by aoengin** [comment]
>  I think choosing an emulator for a device with a lower resolution might let you reproduce the bug.

I could not. What is the resolution of your phone? @YavizGuldalf

**Comment by YavizGuldalf** [comment]
I use a Samsung Galaxy S21 FE 5G, here is the display specifications from [samsung's official website](https://www.samsung.com/in/smartphones/galaxy-s/galaxy-s21-fe-5g-olive-256gb-sm-g990blg4ins/?srsltid=AfmBOorwr65Vjy5OhqW30x26fBF6yGiR1fqahlwdkrb9AuqUm-XZCS9I)

### Size (Main Display)
16.29cm (6.4") full rectangle / 15.89cm (6.3") rounded corners
### Resolution (Main Display)
2340 x 1080 (FHD+)

**Comment by aoengin** [comment]
I couldn’t reproduce the error, but I published a blind fix. Could you check if it helps to resolve the issue on the quiz results page? @YavizGuldalf

**Review by YavizGuldalf — APPROVED** [review]
The fix seems to have worked. You can find the screenshots from my phone below.  I am not merging this issue as @anilanlar is the one assigned as the reviewer in Issue #456, but I approve of these changes.

| Quiz Results Page | Quiz Question Page |
| ----- | - | 
|  | |

**Comment by anilanlar** [comment]
As the dynamic sizing problem is also fixed, I also approve and am merging the changes. Good job!

**Pull request merged**
