### PR TITLE
Search Page Backend Connection (Mobile)

### LINKED ISSUE #663: Mobile: Connect Search to Backend
## Issue Description
We have a basic search in place in the backend, and we should connect our search page to the backend.

## Tasks

- [x] Connect the search page to the backend.
- [x] Display the results correctly.
## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 13/12/2024 - 23: 59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:**15/12/2024 - 23:59

### PR DESCRIPTION
**Pull request by YavizGuldalf**
Fixes #663.
This PR includes a small change to the design of the search page and also connects it to the backend. Notable changes in this PR are the following:

* The search page design has been changed, and the options to sort and filter by tags have been removed.
* The option to filter by content type has been changed to allow search for only a single type of content. Its design has been slightly altered to fill the space that the other two options mentioned above filled.
* The IP has been changed with the BACKEND-DEV deployment IP. (this is a trivial change)
* The placeholders for postcard and comment card have been removed and replaced with the real components.
* The search page has been connected to the backend's 'search/' endpoint, and the results have been transformed so that they are correctly displayed using our existing 'Card' components.

### CODE REVIEW

**Comment by aoengin** [comment]
Generally, it works well, but I created a user with my own name, and the user search doesn't seem to be working properly. Can you check? @YavizGuldalf

**Comment by YavizGuldalf** [comment]
@aoengin I think that has to do with the filtering I added, when searching for users, you cannot see your own user. When I logged in as the user 'admin', I was able to successfully search for and see  the user you mentioned.

**Comment by YavizGuldalf** [comment]
Well now that I think about it, I think it's better to handle this at the source. I will update this PR by changing the UserCard component so that it does not display the Follow/Unfollow button if the username is the same as the logged in user, and I'll also make it redirect to the own profile page instead of other profile.

**Comment by YavizGuldalf** [comment]
It should be fixed now, can you check @aoengin?

**Comment by aoengin** [comment]
Works well, thanks!

**Pull request merged**
