### PR TITLE
MOBILE-331: Create a SignUp Page

### PR DESCRIPTION
**Pull request by aoengin**
Fixes [331](https://github.com/bounswe/bounswe2024group6/issues/331).
I've implemented a signup page with client side checks. It's been implemented in accordance with the mobile mockups. 
Navbar will be fixed once navbar PR is merged.

### CODE REVIEW

**Review by anilanlar — CHANGES_REQUESTED** [review]
- Could you name the file as register.tsx so that we are not going to have confusion in the future.

- Since expo does the routing based on the file name (which is signUp.tsx at the moment) we'd better change it to register.tsx

**Review by YavizGuldalf — COMMENTED** [review]
The code in general looks good. The only comment I have is that we should probably change the `backgroundColor` prop of the inputs to "#ffec99", the color used in the mock-ups. The `backgroundColor` of the 'Sign Up' button should also be similarly changed to "#9775fa". I don't think any other changes are necessary at this point.

**Comment by YavizGuldalf** [comment]
Also, since #317 is now merged the new navigation bar should be added to the top.

**Comment by aoengin** [comment]
> Also, since #317 is now merged the new navigation bar should be added to the top.

The navbar already exists. I was planning to switch to your implementation to standardize it, but there are some issues with your version. We should make some changes on the navbar implementation.

**Comment by aoengin** [comment]
I've rebased and made the requested changes. @YavizGuldalf @anilanlar

**Review by YavizGuldalf — APPROVED** [review]
I have looked through the changes and tested how the UI looks. I don't see any problems, good job.

**Comment by aoengin** [comment]
I've rebased for the second time please merge this PR. @YavizGuldalf @anilanlar

**Comment by YavizGuldalf** [comment]
I think @anilanlar's issues have already been addressed, so I am merging this PR without waiting for his approval.

**Pull request merged**
