### PR TITLE
Lab 6 Pull Request

### PR DESCRIPTION
**Pull request by aoengin**
The team's responsibilities for this Lab are detailed below. This message is quoted directly from the official CMPE 451 Moodle Page.

- > Create a PR dedicated to this lab session where you will link work done in this lab: commits, wiki pages, issues, meeting notes, etc. Start the PR with a commit in a new branch. Then, add commits to the branch, and document all the work in the PR description and comments. The commits should include co-authors, if there are any, see [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). The description and comments should include the names of the main contributors related to the linked work. The PR should be finalized today at 8:00 PM.
- > Document 2 user stories of a group of people each that would use your system in a specific location (e.g. work, Taiwan), time (e.g. morning), and duration (e.g. 15 minutes). The users need not have names, images, etc., but they should have specific demographics. It's not a single person but a group of people with similar characteristics regarding the user story.
- > Substantial commit(s) regarding UX design catered to the above-mentioned user stories.
- > Substantial commit(s) regarding UI similarity between the web and mobile versions of the system.

### CODE REVIEW

**Comment by aoengin** [comment]
Fixes #491.

- Home page is redesigned to improve similarities with web UI.

**Comment by Elifnurdeniz** [comment]
User stories can be found in this [link](https://github.com/bounswe/bounswe2024group6/wiki/Lab%E2%80%906-User-Stories).

**Comment by aoengin** [comment]
Fixes #492.

- Now dark mode feature is available for quiz question page.

**Comment by aoengin** [comment]
Related Issues: 

#489
#490 
#491 
#492 
#495

**Comment by aoengin** [comment]
[Meeting Notes ](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-6) and [Lab Report](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Report-6)

**Review by Elifnurdeniz — APPROVED** [review]

**Pull request merged**
