### PR TITLE
Lab 5 Pull Request

### PR DESCRIPTION
**Pull request by YavizGuldalf**
The team's responsibilities for this Lab are detailed below. This message is quoted directly from the official CMPE 451 Discord channel.

> * Create a PR dedicated to this lab session where you will link work done in this lab: commits, wiki pages, issues, meeting notes, etc. Start the PR with a commit in a new branch. Then, add commits to the branch, and document all the work in the PR description and comments. The commits should include co-authors, if there are any, see [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). The description and comments should include the names of the main contributors related to the linked work. The PR should be finalized today at 8:00 PM.
> *  ⁠Standard selection and documentation, if you have not done so:
>      *  Document the standard in your wiki as to:
>          * what is it for, its benefits,
>          * what are the requirements of following the standard,
>          * how it will be enforced in practice.
>      * ⁠Substantial commit(s) regarding the selected standard,
>     * Substantial commit(s) regarding domain specificity.

### CODE REVIEW

**Comment by yunusemreozdemir** [comment]
Screenshot 2024-11-05 at 16 45 40

**Comment by arastasci** [comment]
We have written the domain specific features we have discussed on [here](https://github.com/bounswe/bounswe2024group6/wiki/Improvements-For-the-Project-for-Domain-Specificity).
Co-Author: @YavizGuldalf

**Comment by YavizGuldalf** [comment]
You can find the detailed research about the selected W3C standard (Activity Stream 2.0) over at the relevat [wiki page](https://github.com/bounswe/bounswe2024group6/wiki/Activity-Streams-2.0-Detailed-Research). You can also find a higher level review of the different W3C standards over [here](https://github.com/bounswe/bounswe2024group6/wiki/W3C-Standards).

**Comment by anilanlar** [comment]
Fixes [#468](url)

- Updated the color palette of forum feed page.

image

**Comment by YavizGuldalf** [comment]
I have added a PressableText component to the mobile app. It can be used in place of Text components in the app to create a pop-up view whenever one of the words in the text are pressed and held. This component may be used to create the pop-up dictionary that we can implement as part of our domain-specific features, which you can find [here](https://github.com/bounswe/bounswe2024group6/wiki/Improvements-For-the-Project-for-Domain-Specificity).

**Comment by aoengin** [comment]
[Lab Report for Lab5 ](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Report-5)

Related Issues:
#479
#480

**Comment by YavizGuldalf** [comment]
[Meeting Notes for Lab 5](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-5)

**Review by Elifnurdeniz — APPROVED** [review]

**Pull request merged**
